### ISSUE TITLE
'APIStrategy.STRATEGY_NAME' does not need quotes

### ISSUE THREAD

**Issue by afrittoli** [IBM-Bluemix-Docs/appid#244]
Using quotes leads to:

```
Error: Unknown authentication strategy "APIStrategy.STRATEGY_NAME"
    at attempt (/Users/andreafrittoli/nodejs/node_modules/passport/lib/middleware/authenticate.js:186:37)
    at authenticate (/Users/andreafrittoli/nodejs/node_modules/passport/lib/middleware/authenticate.js:362:7)
    at Layer.handle [as handle_request] (/Users/andreafrittoli/nodejs/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/andreafrittoli/nodejs/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/andreafrittoli/nodejs/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/andreafrittoli/nodejs/node_modules/express/lib/router/layer.js:95:5)
    at /Users/andreafrittoli/nodejs/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/andreafrittoli/nodejs/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/andreafrittoli/nodejs/node_modules/express/lib/router/index.js:275:10)
    at initialize (/Users/andreafrittoli/nodejs/node_modules/passport/lib/middleware/initialize.js:53:5)
```

The correct code is:

```
app.get('/protected', passport.authenticate(APIStrategy.STRATEGY_NAME, 
```

**Comment by smguilia** [comment]
This is fixed and will go out in the next prod push.
